apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: slow  
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/share
    server: 192.168.1.6
